services:
  app:
    build:
      context: .
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: secret
      ZIPKIN_ENDPOINT: http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
    ports:
      - "8080:8080"
      - "8081:8081"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: catalog
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    shm_size: 2gb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"

volumes:
  postgres-data: {}
  kafka-data: {}
  kafka-metadata: {}
