logging:
  level:
    org.springframework.web: INFO
    ch.qos.logback: WARN
    com.pax8.catalog: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg traceId=%X{traceId} spanId=%X{spanId} %n"

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8081
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      export:
        enabled: true
      endpoint: ${ZIPKIN_ENDPOINT:http://localhost:9411/api/v2/spans}

server:
  max-http-request-header-size: 56KB
  error:
    include-stacktrace: never

spring:
  application:
    name: catalog
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/catalog}
    username: ${POSTGRES_USER:catalog}
    password: ${POSTGRES_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    open-in-view: false
    defer-datasource-initialization: false
  flyway:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/catalog}
    user: ${POSTGRES_USER:catalog}
    password: ${POSTGRES_PASSWORD:secret}
    locations: classpath:db/migration
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
