@id = c32edbbc-10c0-415d-9dfb-45897ef38384

### Get products
GET localhost:8080/products


### Get product
GET localhost:8080/products/{{id}}


### Create product
POST localhost:8080/products
Content-Type: application/json

{
  "name": "Product X1",
  "description": "Description for Product X1",
  "price": 125.05
}


### Update product
PUT localhost:8080/products/{{id}}
Content-Type: application/json

{
  "name": "Product X1",
  "description": "Description for Product X1",
  "price": 125.95
}


### Delete product
DELETE localhost:8080/products/{{id}}
